# Profile Switching
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Common Configurations (Shared between Local and Prod)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.path=/swagger-ui.html
spring.data.web.pageable.serialization-mode=via-dto
spring.jpa.open-in-view=false
server.forward-headers-strategy=framework
spring.jackson.deserialization.fail-on-unknown-properties=false