# Server Port (Dynamic for Cloud)
server.port=${PORT:8080}

# Database Configuration (Cloud Environment Variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA & Liquibase (Strict for Production)
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Hikari Connection Pool settings
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# Cache (Cloud Redis)
spring.cache.type=${SPRING_CACHE_TYPE:redis}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Security
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER:stadium-booking-system}